### ISSUE TITLE
2 papers to appear at COLING

### ISSUE THREAD

**Issue by shirawein** [nert-nlp/AMR-Bibliography#148]
BiBL: AMR Parsing and Generation with Bidirectional Bayesian Learning
Ziming Cheng, Zuchao Li and Hai Zhao

Accounting for Language Effect in the Evaluation of Cross-lingual AMR Parsers
Shira Wein and Nathan Schneider

**Comment by nschneid** [comment]
Have these been added?

**Comment by shirawein** [comment]
I'm adding them now, they just appeared on ACL Anthology
