### ISSUE TITLE
Maybe remove "state-of-the-art" tracker

### ISSUE THREAD

**Issue by flipz357** [nert-nlp/AMR-Bibliography#274]
The webpage seems to display ["state of the art" for parsing](https://github.com/nert-nlp/AMR-Bibliography/blob/f05f72ce007a4c4a79dceecba9f7afc7e4d2f12f/index.html#L38)

But the table doesn't seem maintained anymore. Besides it may be also question worthy [what is the "state of the art" today](https://arxiv.org/abs/2210.06461).

So I'd say that's two arguments for removing this part (for now).

**Comment by nschneid** [comment]
Reworded to make clear it's no longer SOTA
