### ISSUE TITLE
Five LREC-COLING 2024 Papers

### ISSUE THREAD

**Issue by shirawein** [nert-nlp/AMR-Bibliography#297]
CALAMR: Component ALignment for Abstract Meaning Representation
https://aclanthology.org/2024.lrec-main.236.pdf

A Corpus of German Abstract Meaning Representation (DeAMR)
https://aclanthology.org/2024.lrec-main.26.pdf

Leveraging AMR Graph Structure for Better Sequence-to-Sequence AMR Parsing
https://aclanthology.org/2024.lrec-main.903.pdf

Encoding Gesture in Multimodal Dialogue: Creating a Corpus of Multimodal AMR
https://aclanthology.org/2024.lrec-main.515.pdf

GLAMR: Augmenting AMR with GL-VerbNet Event Structure
https://aclanthology.org/2024.lrec-main.685.pdf

**Comment by shirawein** [comment]
Two more--

Anchor and Broadcast: An Eﬀicient Concept Alignment Approach for Evaluation of Semantic Graphs
https://aclanthology.org/2024.lrec-main.94.pdf

ReCAP: Semantic Role Enhanced Caption Generation
https://aclanthology.org/2024.lrec-main.1191.pdf

**Comment by nschneid** [comment]
[Linear Cross-document Event Coreference Resolution with X-AMR](https://aclanthology.org/2024.lrec-main.920)
