### ISSUE TITLE
DMR 2024

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/AMR-Bibliography#299]
- [x] [Accelerating UMR Adoption: Neuro-Symbolic Conversion from AMR-to-UMR with Low Supervision](https://aclanthology.org/2024.dmr-1.15.pdf)
- [x] [The Relative Clauses AMR Parsers Hate Most](https://aclanthology.org/2024.dmr-1.16.pdf)
- [x] [Lexicalized Meaning Representation (LMR)](https://aclanthology.org/2024.dmr-1.11.pdf)
- [x] [Argument Sharing in Meaning Representation Parsing](https://aclanthology.org/2024.dmr-1.9.pdf)
- [x] [YARN is All You Knit: Encoding Multiple Semantic Phenomena with Layers](https://aclanthology.org/2024.dmr-1.8.pdf)

**Comment by shirawein** [comment]
YARN is on already

**Comment by shirawein** [comment]
- [ ] VOLARE - Visual Ontological Language Representation: https://aclanthology.org/2024.dmr-1.7.pdf
