### ISSUE TITLE
Semantic Graph Learning for Trend Prediction from Long Financial Documents

### ISSUE THREAD

**Issue by shirawein** [nert-nlp/AMR-Bibliography#306]
http://www.cs.rpi.edu/~zaki/PaperDir/CIFER24.pdf

**Comment by shirawein** [comment]
I don't see this one in the bib

**Comment by shirawein** [comment]
I don't see this one in the bib

**Comment by xiulinyang** [comment]
Sorry, my bad. I mistakenly took another financial paper as this one. I have just updated the data. Thanks for the reminder!
