### ISSUE TITLE
Towards a Conversion of the Prague Dependency Treebank Data to the Uniform Meaning Representation

### ISSUE THREAD

**Issue by xiulinyang** [nert-nlp/AMR-Bibliography#317]

**Comment by shirawein** [comment]
Just FYI we typically don't add new UMR papers to the AMR Bibliography but up to you!

**Comment by xiulinyang** [comment]
> Just FYI we typically don't add new UMR papers to the AMR Bibliography but up to you!
 I see! Good to know. Thanks! :)
