### ISSUE TITLE
Add papers "Improving Event Detection with Abstract Meaning Representation" and "Abstract Meaning Representation Guided Graph Encoding and Decoding for Joint Information Extraction"

### ISSUE THREAD

**Issue by ablodge** [nert-nlp/AMR-Bibliography#37]
Improving Event Detection with Abstract Meaning Representation
https://www.aclweb.org/anthology/W15-4502/

Abstract Meaning Representation Guided Graph Encoding and Decoding for Joint Information Extraction
(accepted at NAACL 2021)

**Comment by nschneid** [comment]
https://aclanthology.org/2021.naacl-main.4/
