### ISSUE TITLE
Recomendation to pull new papers from arxiv.org search

### ISSUE THREAD

**Issue by bjascob** [nert-nlp/AMR-Bibliography#41]
Thanks for keeping up this list.  I find it very useful and check it regularly for new papers on AMR.  One thing that I've noticed however, is that an [arXiv search](https://arxiv.org/search/?query=%22Abstract+Meaning+Representation%22&searchtype=all&abstracts=show&order=-announced_date_first&size=50) tends to yield a number of results that aren't included on this list.  An arXiv search for "Abstract Meaning Representation" results are generally 100% relevant.  A search for "AMR" returns another grouping, though there are usually a number of false positives or less relevant papers in that grouping.

From the above search you might consider adding...
```
Dynamic Semantic Graph Construction and Reasoning for Explainable Multi-hop Science Question Answering 
Semantic Representation for Dialogue Modeling 
ASQ: Automatically Generating Question-Answer Pairs using AMRs 
Polynomial Graph Parsing with Non-Structural Reentrancies 
```
All of which released in the last few months.

 I can certainly check both places myself, but other users may be interested in this info as well.  Just something to consider.

**Comment by nschneid** [comment]
Thanks, we will add these. I'm happy to say that AMR research is so popular now that it's getting harder to keep tabs on all the new papers...perhaps we should do a monthly arXiv search. And perhaps we should get the word out more so authors know to alert us when they post a new paper.

Glad you're finding this useful and keep the suggestions coming!

**Comment by shirawein** [comment]
- [ ] Weiwen Xu, Huihui Zhang, Deng Cai and Wai Lam; Dynamic Semantic Graph Construction and Reasoning for Explainable Multi-hop Science Question Answering; Findings of the Association for Computational Linguistics: ACL-IJCNLP 2021; https://aclanthology.org/2021.findings-acl.90.pdf
- [ ] Johanna Björklund, Frank Drewes, Anna Jonsson; Polynomial Graph Parsing with Non-Structural Reentrancies; preprint 2021; https://arxiv.org/pdf/2105.02033.pdf
