### ISSUE TITLE
More papers from ACL and starsem

### ISSUE THREAD

**Issue by shirawein** [nert-nlp/AMR-Bibliography#47]
Dependency Patterns of Complex Sentences and Semantic Disambiguation for Abstract Meaning Representation Parsing
Yuki Yamamoto Yuji Matsumoto Taro Watanabe
https://aclanthology.org/2021.starsem-1.20.pdf

Fine-grained Information Extraction from Biomedical Literature based on Knowledge-enriched Abstract Meaning Representation
Zixuan Zhang, Nikolaus Parulian, Heng Ji,
Ahmed S. Elsayed, Skatje Myers, Martha Palmer
https://aclanthology.org/2021.acl-long.489.pdf

Incorporating EDS Graph for AMR Parsing
Ziyi Shou and Fangzhen Lin
https://aclanthology.org/2021.starsem-1.19.pdf

End-to-End AMR Coreference Resolution
Qiankun Fu, Linfeng Song, Wenyu Du, Yue Zhang
https://aclanthology.org/2021.acl-long.324.pdf

XLPT-AMR: Cross-Lingual Pre-Training via Multi-Task Learning for Zero-Shot AMR Parsing and Text Generation
Dongqin Xu, Junhui Li, Muhua Zhu, Min Zhang, Guodong Zhou
https://aclanthology.org/2021.acl-long.73.pdf

**Comment by nschneid** [comment]
From the structured prediction workshop: https://aclanthology.org/2021.spnlp-1.3/
