### ISSUE TITLE
Disjunctive AMR

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/AMR-Bibliography#54]
Manuscript: https://amr.isi.edu/damr.1.0.pdf

**Comment by shirawein** [comment]
Annotation, AMR Extensions

**Comment by shirawein** [comment]
Not sure about year / publication status etc.

**Comment by nschneid** [comment]
To my knowledge it's an unpublished manuscript. The original Banarescu et al. AMR paper mentions it. So let's list as 2013.
