### ISSUE TITLE
EMNLP 2021

### ISSUE THREAD

**Issue by nschneid** [nert-nlp/AMR-Bibliography#56]
LAW-DMR 2021 and EMNLP demo papers on AMR/UMR:

- [x] https://aclanthology.org/2021.emnlp-demo.19/
- [x] https://aclanthology.org/2021.law-1.2/
- [x] https://aclanthology.org/2021.law-1.3/
- [x] https://aclanthology.org/2021.law-1.4/
- [x] https://aclanthology.org/2021.law-1.6/
- [x] https://aclanthology.org/2021.law-1.17/

Also, find titles mentioning AMR at: https://aclanthology.org/events/emnlp-2021/

**Comment by shirawein** [comment]
- [ ] Referenceless Parsing-Based Evaluation of AMR-to-English Generation; Emma Manning, Nathan Schneider; https://aclanthology.org/2021.eval4nlp-1.12/
- [ ] Multilingual AMR Parsing with Noisy Knowledge Distillation; Deng Cai, Xin Li, Jackie Chun-Sing Ho, Lidong Bing, Wai Lam; https://aclanthology.org/2021.findings-emnlp.237/
- [ ] Stacked AMR Parsing with Silver Data; Qingrong Xia, Zhenghua Li, Rui Wang, Min Zhang; https://aclanthology.org/2021.findings-emnlp.406/
- [ ] Smelting Gold and Silver for Improved Multilingual AMR-to-Text Generation; Leonardo F. R. Ribeiro, Jonas Pfeiffer, Yue Zhang, Iryna Gurevych; https://aclanthology.org/2021.emnlp-main.57/
- [ ] Explainable Unsupervised Argument Similarity Rating with Abstract Meaning Representation and Conclusion Generation; Juri Opitz, Philipp Heinisch, Philipp Wiesenbach, Philipp Cimiano, Anette Frank; https://aclanthology.org/2021.argmining-1.3/

**Comment by shirawein** [comment]
- [ ] RepGraph: Visualising and Analysing Meaning Representation Graphs; Jaron Cohen, Roy Cohen, Edan Toledo, Jan Buys; https://aclanthology.org/2021.emnlp-demo.10/
