### ISSUE TITLE
LAW-DMR 2021 Papers

### ISSUE THREAD

**Issue by shirawein** [nert-nlp/AMR-Bibliography#65]
Representing Implicit Positive Meaning of Negated Statements in AMR
Katharina Stein, Lucia Donatelli
https://aclanthology.org/2021.law-1.3/

Classifying Divergences in Cross-lingual AMR Pairs
Shira Wein, Nathan Schneider
https://aclanthology.org/2021.law-1.6/

Intensionalizing Abstract Meaning Representations: Non-Veridicality and Scope
Gregor Williamson, Patrick Elliott, Yuxin Ji
https://aclanthology.org/2021.law-1.17/

**Comment by nschneid** [comment]
See #56
